-- Create charities table
create table public.charities (
  id bigint generated by default as identity primary key,
  name text not null,
  website_url text,
  description text,
  logo_url text, -- Cloudinary URL
  primary_cause_area_id bigint references public.cause_areas(id),
  created_by uuid references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  
  constraint valid_website_url check (
    website_url is null or 
    website_url ~ '^https?://'
  )
);

-- Enable RLS
alter table public.charities enable row level security;

-- Create RLS policies
create policy "Users can manage own charities" on public.charities
  for all to authenticated using (auth.uid() = created_by);

create policy "Users can view all charities" on public.charities
  for select to authenticated using (true);

-- Add indexes for performance
create index idx_charities_created_by on public.charities(created_by);
create index idx_charities_cause_area on public.charities(primary_cause_area_id);