-- Create cause_areas table
create table public.cause_areas (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  color_hex varchar(7), -- For UI theming
  created_by uuid references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table public.cause_areas enable row level security;

-- Create RLS policies
create policy "Users can manage own cause areas" on public.cause_areas
  for all to authenticated using (auth.uid() = created_by);

create policy "Users can view all cause areas" on public.cause_areas
  for select to authenticated using (true);

-- Add index for performance
create index idx_cause_areas_created_by on public.cause_areas(created_by);