-- Create donations table
create table public.donations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  charity_id bigint references public.charities(id) on delete restrict not null,
  amount decimal(12,2) not null check (amount > 0),
  currency varchar(3) not null default 'USD',
  donation_date date not null,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable RLS
alter table public.donations enable row level security;

-- Create RLS policy
create policy "Users can manage own donations" on public.donations
  for all to authenticated using (auth.uid() = user_id);

-- Add indexes for common queries
create index idx_donations_user_date on public.donations(user_id, donation_date desc);
create index idx_donations_user_charity on public.donations(user_id, charity_id);
create index idx_donations_charity on public.donations(charity_id);